-- ===========================================================================
--  Ardevane Operations V1 — schema migration
--  SQL Editor -> New query -> paste -> Run. Safe to run more than once.
--
--  Adds:
--    1. cabins.is_active        archive a cabin instead of deleting it
--    2. cabin_images            a real table, one row per image
--    3. backfill                every existing cabins.image becomes image #0
--
--  Nothing is deleted. cabins.image stays as the cover image, so the current
--  code keeps working while the gallery is added on top.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Archive instead of delete
-- ---------------------------------------------------------------------------
alter table public.cabins
  add column if not exists "is_active" boolean not null default true;

comment on column public.cabins."is_active" is
  'false = archived. Kept for existing bookings, hidden from new/public use.';


-- ---------------------------------------------------------------------------
-- 2. Cabin gallery
-- ---------------------------------------------------------------------------
create table if not exists public.cabin_images (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  "cabinId"   bigint not null references public.cabins (id) on delete cascade,
  url         text   not null,
  position    integer not null default 0
);

create index if not exists cabin_images_cabin_idx
  on public.cabin_images ("cabinId", position);

comment on table public.cabin_images is
  'Gallery images for a cabin. position 0 is the cover.';


-- ---------------------------------------------------------------------------
-- 3. Backfill: the single image each cabin already has becomes image #0
-- ---------------------------------------------------------------------------
insert into public.cabin_images ("cabinId", url, position)
select c.id, c.image, 0
from public.cabins c
where c.image is not null
  and c.image <> ''
  and not exists (
    select 1 from public.cabin_images i
    where i."cabinId" = c.id and i.position = 0
  );


-- ---------------------------------------------------------------------------
-- 4. Row level security for the new table
--    Operations data is for signed-in employees only. This is deliberately
--    narrower than the policies on the older tables.
-- ---------------------------------------------------------------------------
alter table public.cabin_images enable row level security;

drop policy if exists "employees read cabin_images"   on public.cabin_images;
drop policy if exists "employees insert cabin_images" on public.cabin_images;
drop policy if exists "employees update cabin_images" on public.cabin_images;
drop policy if exists "employees delete cabin_images" on public.cabin_images;

create policy "employees read cabin_images" on public.cabin_images
  for select to authenticated using (true);

create policy "employees insert cabin_images" on public.cabin_images
  for insert to authenticated with check (true);

create policy "employees update cabin_images" on public.cabin_images
  for update to authenticated using (true) with check (true);

create policy "employees delete cabin_images" on public.cabin_images
  for delete to authenticated using (true);


-- ---------------------------------------------------------------------------
-- 5. Verification — every row should read OK
-- ---------------------------------------------------------------------------
select 'cabins.is_active' as item,
       case when count(*) > 0 then 'OK' else '*** MISSING ***' end as status
from information_schema.columns
where table_schema = 'public' and table_name = 'cabins' and column_name = 'is_active'

union all
select 'table cabin_images',
       case when count(*) > 0 then 'OK' else '*** MISSING ***' end
from information_schema.tables
where table_schema = 'public' and table_name = 'cabin_images'

union all
select 'images backfilled',
       count(*)::text
from public.cabin_images

union all
select 'cabins total',
       count(*)::text
from public.cabins;


-- ===========================================================================
--  PART 2 — bookings search view
-- ===========================================================================
create or replace view public.bookings_search
with (security_invoker = true) as
select
  b.*,
  g."fullName" as guest_name,
  g.email      as guest_email,
  c.name       as cabin_name
from public.bookings b
left join public.guests g on g.id = b."guestId"
left join public.cabins c on c.id = b."cabinId";

grant select on public.bookings_search to anon, authenticated;


-- ===========================================================================
--  PART 3 — lock the operations data to signed-in employees
--
--  Before this, anyone holding the publishable key (which ships in the
--  browser bundle) could read and write every table. Now only an
--  authenticated employee can. Nothing is deleted.
--
--  The future public guest website will need its own, deliberately narrow,
--  read policy on cabins. Do not re-open these.
-- ===========================================================================
do $$
declare t text;
begin
  foreach t in array array['cabins', 'guests', 'bookings', 'settings', 'cabin_images']
  loop
    execute format('alter table public.%I enable row level security', t);

    execute format('create policy "employees read %s"   on public.%I for select to authenticated using (true)', t, t);
    execute format('create policy "employees insert %s" on public.%I for insert to authenticated with check (true)', t, t);
    execute format('create policy "employees update %s" on public.%I for update to authenticated using (true) with check (true)', t, t);
    execute format('create policy "employees delete %s" on public.%I for delete to authenticated using (true)', t, t);
  end loop;
end $$;

-- Remove anything older that still granted public or anon access
do $$
declare r record;
begin
  for r in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('cabins', 'guests', 'bookings', 'settings', 'cabin_images')
      and policyname not like 'employees %'
  loop
    execute format('drop policy %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;
