-- ===========================================================================
--  Stay folio
--
--  A booking now has a small folio, the way a front desk keeps one:
--
--    services   what the hotel sells besides the night (breakfast, laundry…)
--    charges    what was added to a stay, from the list or written in
--    payments   money the front desk took, cash only for now
--
--  Nothing is totalled in a column. What a stay costs and what is still
--  owed is worked out every time from the rows above, in booking_folios:
--
--    accommodation = the booking's price for the nights
--    extras        = the sum of its charges
--    total         = accommodation + extras
--    paid          = the sum of its payments
--    remaining     = total - paid
--
--  So "isPaid" is no longer the answer to "has this been paid?", and
--  breakfast is no longer part of the booking price: it is a service like
--  any other. The old columns stay on bookings for now, unused.
--
--  Only staff add charges and record payments. A guest can read the folio
--  of their own stay, never write to it.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Services: a short list, priced once, so the desk doesn't type prices
-- ---------------------------------------------------------------------------
create table public.services (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text,
  price numeric(10,2) not null,
  "isActive" boolean not null default true,

  constraint services_name_check check (length(trim(name)) between 1 and 80),
  constraint services_price_check check (price >= 0),
  constraint services_category_check
    check (category in ('food', 'housekeeping', 'other'))
);

create unique index services_name_key on public.services (lower(name));

insert into public.services (name, category, price) values
  ('Breakfast', 'food', 15),
  ('Extra cleaning', 'housekeeping', 30),
  ('Laundry', 'housekeeping', 20);


-- ---------------------------------------------------------------------------
-- 2. Charges: something added to a stay. From the list (serviceId) or
--    written in by hand; either way the description and amount are kept
--    as they were on the day, even if the service changes later.
-- ---------------------------------------------------------------------------
create table public.charges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "bookingId" bigint not null references public.bookings (id) on delete cascade,
  "serviceId" bigint references public.services (id) on delete set null,
  description text not null,
  amount numeric(10,2) not null,
  "createdBy" uuid default auth.uid() references auth.users (id) on delete set null,

  constraint charges_description_check check (length(trim(description)) between 1 and 120),
  constraint charges_amount_check check (amount > 0)
);

create index charges_booking_id_idx on public.charges ("bookingId");


-- ---------------------------------------------------------------------------
-- 3. Payments: money taken at the desk. Cash is the only method; there is
--    no card or online payment in this app.
-- ---------------------------------------------------------------------------
create table public.payments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "bookingId" bigint not null references public.bookings (id) on delete cascade,
  amount numeric(10,2) not null,
  method text not null default 'cash',
  "recordedBy" uuid default auth.uid() references auth.users (id) on delete set null,

  constraint payments_amount_check check (amount > 0),
  constraint payments_method_check check (method = 'cash')
);

create index payments_booking_id_idx on public.payments ("bookingId");


-- ---------------------------------------------------------------------------
-- 4. Who may do what
-- ---------------------------------------------------------------------------
alter table public.services enable row level security;
alter table public.charges enable row level security;
alter table public.payments enable row level security;

revoke all on public.services, public.charges, public.payments from anon;

create policy "Staff see services"
  on public.services for select
  to authenticated
  using ((select public.is_staff()));

create policy "Admins manage services"
  on public.services for all
  to authenticated
  using ((select public.staff_role()) = 'admin')
  with check ((select public.staff_role()) = 'admin');

-- Charges and payments are a record: added, never edited. An admin may
-- delete one to correct a mistake.
create policy "Staff see charges"
  on public.charges for select
  to authenticated
  using ((select public.is_staff()));

create policy "Guests see the charges on their own stays"
  on public.charges for select
  to authenticated
  using (
    "bookingId" in (
      select b.id
      from public.bookings b
      join public.guests g on g.id = b."guestId"
      where g."authUserId" = (select auth.uid())
    )
  );

create policy "Staff add charges"
  on public.charges for insert
  to authenticated
  with check ((select public.is_staff()) and "createdBy" = (select auth.uid()));

create policy "Admins delete charges"
  on public.charges for delete
  to authenticated
  using ((select public.staff_role()) = 'admin');

create policy "Staff see payments"
  on public.payments for select
  to authenticated
  using ((select public.is_staff()));

create policy "Guests see the payments on their own stays"
  on public.payments for select
  to authenticated
  using (
    "bookingId" in (
      select b.id
      from public.bookings b
      join public.guests g on g.id = b."guestId"
      where g."authUserId" = (select auth.uid())
    )
  );

create policy "Staff record payments"
  on public.payments for insert
  to authenticated
  with check ((select public.is_staff()) and "recordedBy" = (select auth.uid()));

create policy "Admins delete payments"
  on public.payments for delete
  to authenticated
  using ((select public.staff_role()) = 'admin');


-- ---------------------------------------------------------------------------
-- 5. The folio of every booking, worked out from the rows. It runs with the
--    caller's rights, so each person sees only the folios they may see.
-- ---------------------------------------------------------------------------
create view public.booking_folios
with (security_invoker = true) as
select
  b.id                                                as "bookingId",
  b."totalPrice"                                      as accommodation,
  coalesce(c.extras, 0)                               as extras,
  b."totalPrice" + coalesce(c.extras, 0)              as total,
  coalesce(p.paid, 0)                                 as paid,
  b."totalPrice" + coalesce(c.extras, 0) - coalesce(p.paid, 0) as remaining
from public.bookings b
left join (
  select "bookingId", sum(amount) as extras
  from public.charges
  group by "bookingId"
) c on c."bookingId" = b.id
left join (
  select "bookingId", sum(amount) as paid
  from public.payments
  group by "bookingId"
) p on p."bookingId" = b.id;

revoke all on public.booking_folios from anon;
grant select on public.booking_folios to authenticated;

-- The bookings list shows what is still owed on each row, so the search
-- view carries the folio too (new columns go at the end).
create or replace view public.bookings_search
with (security_invoker = true) as
select
  b.*,
  g."fullName" as guest_name,
  g.email      as guest_email,
  c.name       as cabin_name,
  f.total      as folio_total,
  f.paid       as folio_paid,
  f.remaining  as folio_remaining
from public.bookings b
left join public.guests g on g.id = b."guestId"
left join public.cabins c on c.id = b."cabinId"
left join public.booking_folios f on f."bookingId" = b.id;


-- ---------------------------------------------------------------------------
-- 6. Move the sample data over to the folio, so every total stays the same:
--    breakfast that was part of a booking price becomes a Breakfast charge,
--    and a booking marked paid gets one cash payment for its whole total.
-- ---------------------------------------------------------------------------
insert into public.charges (created_at, "bookingId", "serviceId", description, amount, "createdBy")
select b.created_at, b.id, s.id, 'Breakfast', b."extrasPrice", null
from public.bookings b
cross join (select id from public.services where name = 'Breakfast') s
where b."extrasPrice" > 0;

insert into public.payments (created_at, "bookingId", amount, method, "recordedBy")
select b.created_at, b.id, b."totalPrice", 'cash', null
from public.bookings b
where b."isPaid"
  and b."totalPrice" > 0
  and b.status not in ('cancelled', 'no_show');

update public.bookings
set "totalPrice" = "totalPrice" - "extrasPrice",
    "extrasPrice" = 0,
    "hasBreakfast" = false
where "extrasPrice" > 0 or "hasBreakfast";

comment on column public.bookings."isPaid" is
  'Unused. Whether a stay is paid comes from booking_folios.';
comment on column public.bookings."hasBreakfast" is
  'Unused. Breakfast is a service charged on the folio.';
comment on column public.bookings."extrasPrice" is
  'Unused. Extras are the charges on the folio.';
comment on column public.settings."breakfastPrice" is
  'Unused. The breakfast price is the Breakfast service.';
