-- ===========================================================================
--  Baseline
--
--  The database exactly as it stood before migrations were versioned (read
--  from the live project on 2026-10-07): the
--  course project's tables, the Ardevane V1 additions (archived cabins,
--  cabin gallery, bookings search) and the access rules of that time.
--  Everything after this file changes it on purpose.
--
--  On the live project this migration is marked as already applied; on a
--  new project it builds the starting point.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table public.cabins (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now(),
  name            text,
  "maxCapacity"   smallint,
  "regularPrice"  smallint,
  discount        smallint,
  description     text,
  image           text,
  is_active       boolean not null default true
);

comment on column public.cabins.is_active is
  'false = archived. Kept for existing bookings, hidden from new/public use.';

create table public.guests (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  "fullName"     text,
  email          text,
  nationality    text,
  "countryFlag"  text,
  "nationalID"   text
);

create table public.settings (
  id                     bigint generated by default as identity primary key,
  created_at             timestamptz not null default now(),
  "minBookingLength"     smallint,
  "maxBookingLength"     smallint,
  "maxGuestsPerBooking"  smallint,
  "breakfastPrice"       real
);

create table public.bookings (
  id              bigint generated by default as identity,
  created_at      timestamptz not null default now(),
  "startDate"     timestamp,
  "endDate"       timestamp,
  "numGuests"     smallint,
  "cabinPrice"    real,
  "extrasPrice"   real,
  "totalPrice"    real,
  status          text,
  "hasBreakfast"  boolean,
  "isPaid"        boolean,
  observations    text,
  "cabinId"       bigint not null,
  "guestId"       bigint,
  "numNights"     integer,
  constraint bookings_pkey primary key (id, "cabinId"),
  -- The names keep the course project's original typos ("cabinID", "gusetID")
  constraint "bookings_cabinID_fkey" foreign key ("cabinId") references public.cabins (id),
  constraint "bookings_gusetID_fkey" foreign key ("guestId") references public.guests (id)
);

create table public.cabin_images (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  "cabinId"   bigint not null references public.cabins (id) on delete cascade,
  url         text not null,
  position    integer not null default 0
);

create index cabin_images_cabin_idx on public.cabin_images ("cabinId", position);

comment on table public.cabin_images is
  'Gallery images for a cabin. position 0 is the cover.';


-- ---------------------------------------------------------------------------
-- Bookings search: one box matches a guest, an email, a cabin or a number
-- ---------------------------------------------------------------------------
create view public.bookings_search
with (security_invoker = true) as
select
  b.*,
  g."fullName" as guest_name,
  g.email      as guest_email,
  c.name       as cabin_name
from public.bookings b
left join public.guests g on g.id = b."guestId"
left join public.cabins c on c.id = b."cabinId";

grant select on public.bookings_search to anon, authenticated;


-- ---------------------------------------------------------------------------
-- Access rules of the time: any signed-in account could do anything, and
-- the guest website read open cabins and the settings while signed out.
-- The next migrations replace all of this.
-- ---------------------------------------------------------------------------
do $$
declare
  t text;
begin
  foreach t in array array['cabins', 'guests', 'bookings', 'settings', 'cabin_images']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy "employees read %s" on public.%I for select to authenticated using (true)', t, t);
    execute format('create policy "employees insert %s" on public.%I for insert to authenticated with check (true)', t, t);
    execute format('create policy "employees update %s" on public.%I for update to authenticated using (true) with check (true)', t, t);
    execute format('create policy "employees delete %s" on public.%I for delete to authenticated using (true)', t, t);
  end loop;
end;
$$;

create policy "Website can read active cabins"
  on public.cabins for select
  to anon
  using (coalesce(is_active, true));

create policy "Website can read settings"
  on public.settings for select
  to anon
  using (true);


-- ---------------------------------------------------------------------------
-- Storage: the two buckets in use (cabin-images, avatars) plus two leftovers
-- from the course project (cabin-image, avatar). Anyone could upload, and in
-- cabin-image also replace and delete.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values
  ('cabin-images', 'cabin-images', true),
  ('avatars', 'avatars', true),
  ('cabin-image', 'cabin-image', true),
  ('avatar', 'avatar', true)
on conflict (id) do update set public = true;

create policy "oasis storage read" on storage.objects
  for select to anon, authenticated
  using (bucket_id in ('cabin-images', 'avatars'));

create policy "oasis storage write" on storage.objects
  for insert to anon, authenticated
  with check (bucket_id in ('cabin-images', 'avatars'));

create policy "Allow all opriations 13tkvp3_0" on storage.objects
  for select to public
  using (bucket_id = 'cabin-image');

create policy "Allow all opriations 13tkvp3_1" on storage.objects
  for insert to public
  with check (bucket_id = 'cabin-image');

create policy "Allow all opriations 13tkvp3_2" on storage.objects
  for update to public
  using (bucket_id = 'cabin-image');

create policy "Allow all opriations 13tkvp3_3" on storage.objects
  for delete to public
  using (bucket_id = 'cabin-image');
