-- ===========================================================================
--  Stay requests
--
--  While a guest is checked in, they can ask the hotel for something from
--  My Stay: breakfast from a small menu, housekeeping, help, or a repair.
--  It is one kind of record for all four:
--
--    requests        what was asked, for which stay, and where it stands
--    request_items   for breakfast only: the dishes and how many
--
--  Every request goes new → in_progress → completed. The apps word the
--  steps to fit (breakfast is "Preparing" then "Delivered", a repair is
--  "Fixed"), but there is only this one lifecycle.
--
--  The active stay is simply the guest's checked-in booking. Guests create
--  requests only through create_stay_request(), which checks exactly that,
--  so nobody can ask for anything before arrival or after checkout. Only
--  staff move a request on.
--
--  When a breakfast order is completed (delivered), its price is added to
--  the stay's folio as one charge. The charge points back at the request,
--  and a request can have only one, so it is never charged twice.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. The breakfast menu is part of the services list, marked as "menu", so
--    there is one list of what the hotel sells
-- ---------------------------------------------------------------------------
alter table public.services drop constraint services_category_check;
alter table public.services
  add constraint services_category_check
    check (category in ('food', 'housekeeping', 'menu', 'other'));

insert into public.services (name, category, price) values
  ('Eggs & Toast', 'menu', 8),
  ('Pancakes', 'menu', 7),
  ('Coffee', 'menu', 3),
  ('Juice', 'menu', 3);

-- Signed-in guests may read the menu, nothing else on the list
create policy "Guests see the menu"
  on public.services for select
  to authenticated
  using (category = 'menu' and "isActive");


-- ---------------------------------------------------------------------------
-- 2. Requests and their items
-- ---------------------------------------------------------------------------
create table public.requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "bookingId" bigint not null references public.bookings (id) on delete cascade,
  type text not null,
  status text not null default 'new',
  title text not null,
  note text,
  priority text not null default 'normal',
  "requestedFor" time,
  "completedAt" timestamptz,
  "createdBy" uuid default auth.uid() references auth.users (id) on delete set null,

  constraint requests_type_check
    check (type in ('breakfast', 'housekeeping', 'support', 'maintenance')),
  constraint requests_status_check
    check (status in ('new', 'in_progress', 'completed')),
  constraint requests_priority_check check (priority in ('normal', 'urgent')),
  constraint requests_title_check check (length(trim(title)) between 1 and 120),
  constraint requests_note_check check (note is null or length(note) <= 1000)
);

create index requests_booking_id_idx on public.requests ("bookingId");
create index requests_open_idx on public.requests (status) where status <> 'completed';

create table public.request_items (
  id bigint generated by default as identity primary key,
  "requestId" bigint not null references public.requests (id) on delete cascade,
  "serviceId" bigint references public.services (id) on delete set null,
  name text not null,
  "unitPrice" numeric(10,2) not null,
  quantity integer not null,

  constraint request_items_price_check check ("unitPrice" >= 0),
  constraint request_items_quantity_check check (quantity between 1 and 20)
);

create index request_items_request_id_idx on public.request_items ("requestId");

-- The charge a completed request added to the folio, if it cost anything.
-- Unique, so one request can never be charged twice.
alter table public.charges
  add column "requestId" bigint unique references public.requests (id) on delete set null;


-- ---------------------------------------------------------------------------
-- 3. Who may do what. Guests read the requests of their own stays; they
--    create them only through the function below and never change them.
--    Staff see and move on every request.
-- ---------------------------------------------------------------------------
alter table public.requests enable row level security;
alter table public.request_items enable row level security;

revoke all on public.requests, public.request_items from anon;

create policy "Staff see requests"
  on public.requests for select
  to authenticated
  using ((select public.is_staff()));

create policy "Staff update requests"
  on public.requests for update
  to authenticated
  using ((select public.is_staff()))
  with check ((select public.is_staff()));

create policy "Guests see the requests of their own stays"
  on public.requests for select
  to authenticated
  using (
    "bookingId" in (
      select b.id
      from public.bookings b
      join public.guests g on g.id = b."guestId"
      where g."authUserId" = (select auth.uid())
    )
  );

create policy "Staff see request items"
  on public.request_items for select
  to authenticated
  using ((select public.is_staff()));

create policy "Guests see the items of their own requests"
  on public.request_items for select
  to authenticated
  using (
    "requestId" in (
      select r.id
      from public.requests r
      join public.bookings b on b.id = r."bookingId"
      join public.guests g on g.id = b."guestId"
      where g."authUserId" = (select auth.uid())
    )
  );


-- ---------------------------------------------------------------------------
-- 4. create_stay_request: the only way a guest asks for something. It finds
--    the guest's checked-in booking itself; without one there is nothing to
--    ask for. A breakfast order lists dishes from the menu as
--    [{"serviceId": 12, "quantity": 2}], priced here, never by the browser.
-- ---------------------------------------------------------------------------
create or replace function public.create_stay_request(
  p_type text,
  p_title text default null,
  p_note text default null,
  p_priority text default 'normal',
  p_requested_for time default null,
  p_items jsonb default null
)
returns public.requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_booking_id bigint;
  v_request    public.requests%rowtype;
  v_item       jsonb;
  v_service    public.services%rowtype;
  v_quantity   integer;
  v_title      text := nullif(left(trim(p_title), 120), '');
  v_names      text[] := '{}';
begin
  if auth.uid() is null then
    raise exception 'You need to be signed in' using errcode = '28000';
  end if;

  select b.id into v_booking_id
  from public.bookings b
  join public.guests g on g.id = b."guestId"
  where g."authUserId" = auth.uid()
    and b.status = 'checked_in'
  order by b."startDate" desc
  limit 1;

  if v_booking_id is null then
    raise exception 'Requests open once you have checked in' using errcode = '22023';
  end if;

  if p_type is null or p_type not in ('breakfast', 'housekeeping', 'support', 'maintenance') then
    raise exception 'Please choose what you need' using errcode = '22023';
  end if;

  if p_type = 'breakfast' then
    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
      raise exception 'Please choose something from the menu' using errcode = '22023';
    end if;
  elsif v_title is null then
    raise exception 'Please say what you need' using errcode = '22023';
  end if;

  insert into public.requests (
    "bookingId", type, title, note, priority, "requestedFor", "createdBy"
  )
  values (
    v_booking_id,
    p_type,
    coalesce(v_title, 'Breakfast'),
    nullif(left(trim(p_note), 1000), ''),
    case when p_type = 'maintenance' and p_priority = 'urgent' then 'urgent' else 'normal' end,
    case when p_type = 'breakfast' then p_requested_for end,
    auth.uid()
  )
  returning * into v_request;

  if p_type = 'breakfast' then
    for v_item in select * from jsonb_array_elements(p_items) loop
      select * into v_service
      from public.services
      where id = (v_item ->> 'serviceId')::bigint
        and category = 'menu'
        and "isActive";

      if not found then
        raise exception 'That dish is not on the menu any more' using errcode = '22023';
      end if;

      v_quantity := coalesce((v_item ->> 'quantity')::integer, 1);

      if v_quantity < 1 or v_quantity > 20 then
        raise exception 'Choose between 1 and 20 of each dish' using errcode = '22023';
      end if;

      insert into public.request_items ("requestId", "serviceId", name, "unitPrice", quantity)
      values (v_request.id, v_service.id, v_service.name, v_service.price, v_quantity);

      v_names := v_names || (v_service.name || ' × ' || v_quantity);
    end loop;

    -- The title says what was ordered, so every list can show it as is
    update public.requests
    set title = left(array_to_string(v_names, ', '), 120)
    where id = v_request.id
    returning * into v_request;
  end if;

  return v_request;
end;
$$;

revoke execute on function public.create_stay_request(text, text, text, text, time, jsonb) from public, anon;
grant execute on function public.create_stay_request(text, text, text, text, time, jsonb) to authenticated;


-- ---------------------------------------------------------------------------
-- 5. Moving a request on. A completed request stays completed; completing
--    one stamps the time, and a paid one adds its charge to the folio.
-- ---------------------------------------------------------------------------
create or replace function private.check_request_status_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  if old.status = 'completed' then
    raise exception 'This request is already completed' using errcode = '22023';
  end if;

  if new.status = 'completed' then
    new."completedAt" := now();
  end if;

  return new;
end;
$$;

create trigger requests_status_change
  before update of status on public.requests
  for each row
  execute function private.check_request_status_change();

create or replace function private.charge_completed_request()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_total numeric;
begin
  select sum("unitPrice" * quantity) into v_total
  from public.request_items
  where "requestId" = new.id;

  if coalesce(v_total, 0) > 0 then
    insert into public.charges ("bookingId", description, amount, "createdBy", "requestId")
    values (
      new."bookingId",
      left('Breakfast: ' || new.title, 120),
      v_total,
      auth.uid(),
      new.id
    )
    on conflict ("requestId") do nothing;
  end if;

  return new;
end;
$$;

create trigger requests_completed_charge
  after update of status on public.requests
  for each row
  when (new.status = 'completed' and old.status <> 'completed')
  execute function private.charge_completed_request();
